version: '2'
services:
  vocab-reverseproxy:
    image: idsvocabularyprovider/reverseproxy-vocol
    ports:
    - "443:443" # IDS-HTTP API
    - "8080:8080" # Self-Description

  vocab-core:
    image: idsvocabularyprovider/eis-vocab 
    volumes:
      - ./../reverseproxy-vocol/cert:/etc/cert/
    environment:
    - SPARQL_ENDPOINT=http://vocab-fuseki:3030/connectorData
    - VOCOL_ENDPOINT=http://vocab-vocol:8888
    - SHACL_VALIDATION=false
#    - DAPS_VALIDATE_INCOMING=true
    expose:
    - "8080"

  vocab-fuseki:
    image: idsvocabularyprovider/fuseki
    volumes:
      - vocab-fuseki:/fuseki
    expose:
    - "3030"
    ports:
    - "3030:3030"

  vocab-vocol:
    image: registry.gitlab.cc-asp.fraunhofer.de/vocoreg/public-ids-vp/vocol:latest
    expose:
    - "8888"
    ports:
    - "8888:8888"
    command: [ "npm", "start","8888", "3030", "http://vocab-fuseki"]
    
  vocab-prometheus:
    image: prom/prometheus:v2.20.1
    ports:
    - 9090:9090
    volumes:
    - ../grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - vocab-vocol    

  vocab-grafana:
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    image: grafana/grafana:7.1.5
    ports:
    - 3000:3000
    volumes:
    - ../grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    - ../grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
    - vocab-prometheus

volumes:
    vocab-fuseki:
